### ISSUE TITLE
error occurs in the HandleUpdate function of the CallbackQuery package

### ISSUE THREAD

**Issue by lalrochhara** [PaulSonOfLars/gotgbot#99] opened 2023-08-08 07:45 UTC
# Bugs

we have error from here i'm not sure about golang, but our bot mention that this line when we try to change bot languages :
```
github.com/PaulSonOfLars/gotgbot/v2/ext/handlers.CallbackQuery.HandleUpdate(...)
/go/pkg/mod/github.com/!paul!son!of!lars/gotgbot/v2@vgithub.com/PaulSonOfLars/gotgbot/v2/ext/handlers.CallbackQuery.HandleUpdate(...)
/go/pkg/mod/github.com/!paul!son!of!lars/gotgbot/v2@v2.0.0-rc.20/ext/handlers/callbackquery.go:25
/ext/handlers/callbackquery.go:25
```
 

# System information:

- Operating System + ubuntu latest
- Output of `go version`: v2.0.0-rc20
- Library version (as seen in `go.mod` file): vgo1.19

# Any other information, logs, or outputs that you would like to share?

this is error log when we click our bot languages change button, also our button isn't work too.

```
github.com/PaulSonOfLars/gotgbot/v2/ext/handlers.CallbackQuery.HandleUpdate(...)
        /go/pkg/mod/github.com/!paul!son!of!lars/gotgbot/v2@v2.0.0-rc.20/ext/handlers/callbackquery.go:25
github.com/PaulSonOfLars/gotgbot/v2/ext.(*Dispatcher).iterateOverHandlerGroups(0x4000191c20, 0x0?, 0x1?)
        /go/pkg/mod/github.com/!paul!son!of!lars/gotgbot/v2@v2.0.0-rc.20/ext/dispatcher.go:270 +0x134
github.com/PaulSonOfLars/gotgbot/v2/ext.(*Dispatcher).ProcessUpdate(0x4000191c20, 0x40001a4e00, 0x500?, 0x78b0c0?)
        /go/pkg/mod/github.com/!paul!son!of!lars/gotgbot/v2@v2.0.0-rc.20/ext/dispatcher.go:256 +0x8c
github.com/PaulSonOfLars/gotgbot/v2/ext.(*Dispatcher).ProcessRawUpdate(0x0?, 0x40005aa4e0?, {0x40002d0f00, 0x4b9, 0x500})
        /go/pkg/mod/github.com/!paul!son!of!lars/gotgbot/v2@v2.0.0-rc.20/ext/dispatcher.go:234 +0xac
github.com/PaulSonOfLars/gotgbot/v2/ext.(*Dispatcher).Start.func1({0x40002d0f00?, 0x78244?, 0x0?})
        /go/pkg/mod/github.com/!paul!son!of!lars/gotgbot/v2@v2.0.0-rc.20/ext/dispatcher.go:191 +0x6c
created by github.com/PaulSonOfLars/gotgbot/v2/ext.(*Dispatcher).Start
        /go/pkg/mod/github.com/!paul!son!of!lars/gotgbot/v2@v2.0.0-rc.20/ext/dispatcher.go:181 +0x34
```

**Comment by PaulSonOfLars** [comment] 2023-08-08 08:05
Hi! Sorry to hear you're having an issue.

Would it be possible for you to share how to reproduce this error with some code?
Either with a link to the repo where you're seeing this, or a minimal reproduction example here, would be great.
A full stack trace would also be very helpful!

**Comment by PaulSonOfLars** [comment] 2023-09-02 15:49
Closing due to lack of information - please reopen if you have anything else to add.

**Closed as completed by PaulSonOfLars** 2023-09-02 15:49 UTC
